### ISSUE TITLE
ttl setting ?

### ISSUE THREAD

**Issue by ipeony** [killme2008/xmemcached#48]
Is there a ttl setting to disconnect conntection in pool after a specific time?

**Comment by killme2008** [comment]
I don't recommend users to use xmemcached connection pool in production, because xmemcached is java NIO based, only one connection is enough. the connection pool doesn't provide performance improvement in in general unless  in your own test it does.

Event using connection pool, the pool size should be small, so xmemcached doesn't provide any options to control pool behavior.

**Comment by ipeony** [comment]
I get it,thanks very much.
